server:
  port: 9001
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: subject-microservice
          uri: http://localhost:8001/
          predicates:
            - Path=/subjects/**
        - id: book-microservice
          uri: http://localhost:8002/
          predicates:
            - Path=/books/**